// <auto-generated />
namespace BetApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modeltest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modeltest));
        
        string IMigrationMetadata.Id
        {
            get { return "201307062313015_modeltest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
